language: c # not really, but using make
sudo: required

# pandoc is used to generate the output files
# the pandoc version in the package management system is a tad old though
# so tables don't turn out nice
# install a recent version locally
before_install:
  - wget https://github.com/jgm/pandoc/releases/download/1.19.2.1/pandoc-1.19.2.1-1-amd64.deb
  - sudo dpkg -i pandoc-1.19.2.1-1-amd64.deb

# pandoc needs LaTeX for pdf output
# here the versions from the package system are ok
addons:
  apt:
    packages:
      texlive
      lmodern

# the build step, details in the Makefile
script:
  make all

# for tagged versions, deploy the built files to github
deploy:
  provider: releases
  api_key:
    secure: $GH_TOKEN
  file_glob: true
  file: out/*
  skip_cleanup: true
  on:
    tags: true
